# GitHub Actions workflow to build Go projects on pull requests
name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Find and build all Go modules
        run: |
          find . -name 'go.mod' -execdir go build ./... \;

      - name: Run go vet
        run: |
          find . -name 'go.mod' -execdir go vet ./... \;

      - name: Run go test
        run: |
          find . -name 'go.mod' -execdir go test -v ./... \;
